"""Helpers for sqldbagent long-term memory stored in LangGraph stores."""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

from pydantic import BaseModel, Field

from sqldbagent.core.agent_context import build_snapshot_prompt_context
from sqldbagent.core.config import AppSettings
from sqldbagent.snapshot.models import SnapshotBundleModel

_DATABASE_MEMORY_KEY = "active-database-context"


class DatabaseMemoryRecord(BaseModel):
    """Durable datasource/schema memory stored in LangGraph stores.

    Attributes:
        datasource_name: Canonical datasource name.
        schema_name: Optional schema scope.
        snapshot_id: Snapshot identifier that seeded the autogenerated context.
        snapshot_summary: Human-readable latest snapshot summary.
        autogenerated_context: Snapshot-derived context prepared for prompt injection.
        remembered_notes: User or agent notes worth carrying across sessions.
        prompt_instructions: Extra instructions that should be injected into the prompt.
        preferred_tables: High-signal tables the user keeps focusing on.
        updated_at: Last time the memory record was written.
    """

    datasource_name: str
    schema_name: str | None = None
    snapshot_id: str | None = None
    snapshot_summary: str | None = None
    autogenerated_context: str | None = None
    remembered_notes: list[str] = Field(default_factory=list)
    prompt_instructions: str | None = None
    preferred_tables: list[str] = Field(default_factory=list)
    updated_at: datetime = Field(default_factory=lambda: datetime.now(UTC))

    @property
    def summary(self) -> str | None:
        """Return a concise summary line for UI and state surfaces."""

        if self.snapshot_summary:
            return self.snapshot_summary
        if self.remembered_notes:
            return self.remembered_notes[0]
        return None


def build_database_memory_namespace(
    settings: AppSettings,
    *,
    datasource_name: str,
    schema_name: str | None,
) -> tuple[str, ...]:
    """Build the namespace used for sqldbagent database memory records.

    Args:
        settings: Application settings.
        datasource_name: Canonical datasource name.
        schema_name: Optional schema scope.

    Returns:
        tuple[str, ...]: Namespaced path for the store entry.
    """

    return (
        settings.agent.memory.namespace_prefix,
        "database-memory",
        datasource_name,
        schema_name or "__all__",
    )


def load_database_memory(
    store: Any | None,
    *,
    settings: AppSettings,
    datasource_name: str,
    schema_name: str | None,
) -> DatabaseMemoryRecord | None:
    """Load a persisted datasource/schema memory record.

    Args:
        store: LangGraph store instance, when available.
        settings: Application settings.
        datasource_name: Canonical datasource name.
        schema_name: Optional schema scope.

    Returns:
        DatabaseMemoryRecord | None: Parsed store payload when present.
    """

    if store is None or settings.agent.memory.backend == "disabled":
        return None
    item = store.get(
        build_database_memory_namespace(
            settings,
            datasource_name=datasource_name,
            schema_name=schema_name,
        ),
        _DATABASE_MEMORY_KEY,
    )
    if item is None:
        return None
    return DatabaseMemoryRecord.model_validate(item.value)


def save_database_memory(
    store: Any | None,
    *,
    settings: AppSettings,
    record: DatabaseMemoryRecord,
) -> DatabaseMemoryRecord | None:
    """Persist one datasource/schema memory record into the LangGraph store.

    Args:
        store: LangGraph store instance, when available.
        settings: Application settings.
        record: Memory record to persist.

    Returns:
        DatabaseMemoryRecord | None: Persisted record, or `None` when no store exists.
    """

    if store is None or settings.agent.memory.backend == "disabled":
        return None
    payload = record.model_copy(update={"updated_at": datetime.now(UTC)})
    store.put(
        build_database_memory_namespace(
            settings,
            datasource_name=record.datasource_name,
            schema_name=record.schema_name,
        ),
        _DATABASE_MEMORY_KEY,
        payload.model_dump(mode="json"),
    )
    return payload


def sync_database_memory_from_snapshot(
    store: Any | None,
    *,
    settings: AppSettings,
    datasource_name: str,
    schema_name: str | None,
    snapshot: SnapshotBundleModel,
) -> DatabaseMemoryRecord | None:
    """Upsert store memory from the latest saved snapshot.

    Existing user-authored notes and prompt instructions are preserved while the
    autogenerated snapshot-derived context is refreshed.

    Args:
        store: LangGraph store instance, when available.
        settings: Application settings.
        datasource_name: Canonical datasource name.
        schema_name: Optional schema scope.
        snapshot: Snapshot used to refresh the memory payload.

    Returns:
        DatabaseMemoryRecord | None: Persisted memory record when a store exists.
    """

    existing = load_database_memory(
        store,
        settings=settings,
        datasource_name=datasource_name,
        schema_name=schema_name,
    )
    autogenerated_context = build_snapshot_prompt_context(
        datasource_name=datasource_name,
        settings=settings,
        schema_name=schema_name,
    )
    record = DatabaseMemoryRecord(
        datasource_name=datasource_name,
        schema_name=schema_name,
        snapshot_id=snapshot.snapshot_id,
        snapshot_summary=snapshot.summary,
        autogenerated_context=autogenerated_context,
        remembered_notes=[] if existing is None else list(existing.remembered_notes),
        prompt_instructions=None if existing is None else existing.prompt_instructions,
        preferred_tables=[] if existing is None else list(existing.preferred_tables),
    )
    return save_database_memory(store, settings=settings, record=record)


def remember_database_context(
    store: Any | None,
    *,
    settings: AppSettings,
    datasource_name: str,
    schema_name: str | None,
    notes: list[str],
    prompt_instructions: str | None = None,
    preferred_tables: list[str] | None = None,
    merge: bool = True,
) -> DatabaseMemoryRecord | None:
    """Persist user- or agent-supplied database context into long-term memory.

    Args:
        store: LangGraph store instance, when available.
        settings: Application settings.
        datasource_name: Canonical datasource name.
        schema_name: Optional schema scope.
        notes: Free-form notes worth remembering for future runs.
        prompt_instructions: Extra instructions to inject into the effective prompt.
        preferred_tables: Optional preferred table list.
        merge: Whether to merge with the existing record.

    Returns:
        DatabaseMemoryRecord | None: Persisted memory record when a store exists.
    """

    existing = (
        load_database_memory(
            store,
            settings=settings,
            datasource_name=datasource_name,
            schema_name=schema_name,
        )
        if merge
        else None
    )
    deduped_notes = _dedupe_preserve_order(
        [
            *([] if existing is None else existing.remembered_notes),
            *[note.strip() for note in notes if note.strip()],
        ]
    )
    preferred = _dedupe_preserve_order(
        [
            *([] if existing is None else existing.preferred_tables),
            *(
                []
                if preferred_tables is None
                else [item.strip() for item in preferred_tables if item.strip()]
            ),
        ]
    )
    record = DatabaseMemoryRecord(
        datasource_name=datasource_name,
        schema_name=schema_name,
        snapshot_id=None if existing is None else existing.snapshot_id,
        snapshot_summary=None if existing is None else existing.snapshot_summary,
        autogenerated_context=(
            None if existing is None else existing.autogenerated_context
        ),
        remembered_notes=deduped_notes,
        prompt_instructions=(
            prompt_instructions.strip()
            if prompt_instructions is not None and prompt_instructions.strip()
            else (None if existing is None else existing.prompt_instructions)
        ),
        preferred_tables=preferred,
    )
    return save_database_memory(store, settings=settings, record=record)


def render_database_memory_prompt_context(
    record: DatabaseMemoryRecord | None,
) -> str | None:
    """Render a stored memory record into an agent-facing prompt block.

    Args:
        record: Persisted memory payload when available.

    Returns:
        str | None: Prompt-ready context block, or `None`.
    """

    if record is None:
        return None
    parts: list[str] = []
    if record.snapshot_summary:
        parts.append(f"Latest remembered snapshot summary: {record.snapshot_summary}")
    if record.autogenerated_context:
        parts.append(f"Autogenerated database context:\n{record.autogenerated_context}")
    if record.preferred_tables:
        parts.append(
            "Preferred tables: " + ", ".join(sorted(set(record.preferred_tables)))
        )
    if record.remembered_notes:
        parts.append(
            "Remembered notes:\n"
            + "\n".join(f"- {note}" for note in record.remembered_notes)
        )
    if record.prompt_instructions:
        parts.append("Remembered prompt instructions:\n" + record.prompt_instructions)
    return "\n\n".join(part for part in parts if part.strip()) or None


def _dedupe_preserve_order(values: list[str]) -> list[str]:
    """Return stable-order unique strings."""

    seen: set[str] = set()
    deduped: list[str] = []
    for value in values:
        if value in seen:
            continue
        seen.add(value)
        deduped.append(value)
    return deduped
