"""LangGraph long-term memory integration tests."""

from __future__ import annotations

from uuid import uuid4

import pytest
from langchain_core.messages import AIMessage

from sqldbagent.adapters.langgraph import (
    create_sync_postgres_checkpointed_agent,
    create_sync_postgres_store,
)
from sqldbagent.adapters.langgraph.memory import load_database_memory
from sqldbagent.core.bootstrap import build_service_container
from sqldbagent.core.config import AgentMemorySettings
from tests.helpers import ToolReadyFakeMessagesListChatModel


@pytest.mark.integration
def test_sync_langgraph_agent_persists_database_memory_in_postgres_store(
    live_postgres_settings,
    live_postgres_schema: str,
) -> None:
    """Persist snapshot-derived context into the real Postgres store."""

    settings = live_postgres_settings.model_copy(
        deep=True,
        update={
            "agent": live_postgres_settings.agent.model_copy(
                update={
                    "memory": AgentMemorySettings(
                        backend="postgres",
                        postgres_url=live_postgres_settings.agent.checkpoint.postgres_url,
                        auto_setup=True,
                        auto_sync_from_snapshot=True,
                        auto_create_snapshot_if_missing=True,
                    )
                }
            )
        },
    )
    container = build_service_container("postgres", settings=settings)
    try:
        with create_sync_postgres_checkpointed_agent(
            services=container,
            model=ToolReadyFakeMessagesListChatModel(
                responses=[AIMessage(content="memory integration ok")]
            ),
            datasource_name="postgres",
            settings=settings,
            schema_name=live_postgres_schema,
        ) as agent:
            result = agent.invoke(
                {
                    "messages": [
                        {"role": "user", "content": "Say memory integration ok"}
                    ]
                },
                config={"configurable": {"thread_id": f"memory-{uuid4()}"}},
            )
    finally:
        container.close()

    if "messages" not in result:
        raise AssertionError(result)

    with create_sync_postgres_store(settings=settings) as store:
        record = load_database_memory(
            store,
            settings=settings,
            datasource_name="postgres",
            schema_name=live_postgres_schema,
        )

    if record is None:
        raise AssertionError("Expected a persisted database memory record")
    if record.snapshot_id is None:
        raise AssertionError(record)
    if (
        record.autogenerated_context is None
        or "Relationship Highlights:" not in record.autogenerated_context
    ):
        raise AssertionError(record)
