"""Prompt export models."""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

from pydantic import BaseModel, Field


class PromptSectionModel(BaseModel):
    """Structured prompt section for stored prompt bundles.

    Attributes:
        title: Human-readable section title.
        content: Section body text.
    """

    title: str
    content: str


class PromptExplorationModel(BaseModel):
    """Persisted live exploration block for one datasource/schema pair.

    Attributes:
        datasource_name: Datasource identifier.
        schema_name: Schema represented by the exploration block.
        snapshot_id: Snapshot identifier used as the exploration baseline.
        generated_at: Timestamp of the live read-only exploration pass.
        focus_tables: Tables explored to build the context block.
        summary: Human-readable summary for dashboards and logs.
        context: Prompt-ready exploration text derived from live profiling.
        token_estimates: Cached token estimates for the exploration text.
    """

    datasource_name: str
    schema_name: str
    snapshot_id: str | None = None
    generated_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    focus_tables: list[str] = Field(default_factory=list)
    summary: str | None = None
    context: str = ""
    token_estimates: dict[str, int | str | None] = Field(default_factory=dict)


class PromptEnhancementModel(BaseModel):
    """Persisted prompt-enhancement artifact for one datasource/schema pair.

    Attributes:
        datasource_name: Datasource identifier.
        schema_name: Schema represented by the enhancement artifact.
        snapshot_id: Latest snapshot identifier used to generate DB-aware guidance.
        created_at: Enhancement creation timestamp.
        updated_at: Most recent enhancement update timestamp.
        generated_context_version: Version of the autogenerated prompt-context
            format so regenerated guidance can supersede older artifacts.
        content_hash: Deterministic content hash for persistence and reload checks.
        summary: Human-readable summary for dashboards and prompt exports.
        active: Whether the enhancement should be merged into dynamic prompts.
        generated_context: Deterministic DB-aware guidance derived from the snapshot.
        token_estimates: Cached token estimates for the generated prompt layers.
        exploration: Optional saved live exploration block layered into prompts.
        user_context: Freeform user context or domain notes layered on top.
        business_rules: Business-specific caveats, rules, or interpretation notes.
        additional_effective_context: Extra prompt instructions merged directly
            into the effective system prompt.
        answer_style: Preferred answer style for downstream agent responses.
    """

    datasource_name: str
    schema_name: str
    snapshot_id: str | None = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    generated_context_version: int = 1
    content_hash: str | None = None
    summary: str | None = None
    active: bool = True
    generated_context: str = ""
    token_estimates: dict[str, int | str | None] = Field(default_factory=dict)
    exploration: PromptExplorationModel | None = None
    user_context: str | None = None
    business_rules: str | None = None
    additional_effective_context: str | None = None
    answer_style: str | None = None


class PromptBundleModel(BaseModel):
    """Persisted prompt bundle derived from a stored schema snapshot.

    Attributes:
        snapshot_id: Source snapshot identifier.
        datasource_name: Datasource identifier.
        schema_name: Schema represented by the bundle.
        created_at: Prompt-bundle creation timestamp.
        content_hash: Deterministic content hash for the bundle.
        summary: Human-readable summary for downstream tools and docs.
        base_system_prompt: Prompt rendered before enhancement layers are applied.
        system_prompt: Final rendered prompt used by agent surfaces.
        sections: Structured prompt sections for human review and reuse.
        enhancement: Optional prompt-enhancement artifact merged into the bundle.
        token_estimates: Cached token estimates for the saved prompt bundle.
        state_seed: Initial agent state payload derived from stored artifacts.
    """

    snapshot_id: str
    datasource_name: str
    schema_name: str
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    content_hash: str | None = None
    summary: str | None = None
    base_system_prompt: str
    system_prompt: str
    sections: list[PromptSectionModel] = Field(default_factory=list)
    enhancement: PromptEnhancementModel | None = None
    token_estimates: dict[str, int | str | None] = Field(default_factory=dict)
    state_seed: dict[str, Any] = Field(default_factory=dict)
