name: Docs

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pdm install -G :all

      - name: Build Sphinx docs
        run: make docs
